# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 280)
        Dialog.setStyleSheet("background-color: rgb(52, 52, 59);")
        self.enterInputFilePushButton = QtWidgets.QPushButton(Dialog)
        self.enterInputFilePushButton.setGeometry(QtCore.QRect(490, 30, 71, 31))
        self.enterInputFilePushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: 0;\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(239, 239, 239);\n"
"color: rgb(255, 255, 255);")
        self.enterInputFilePushButton.setObjectName("enterInputFilePushButton")
        self.enterInputFilePushButton_2 = QtWidgets.QPushButton(Dialog)
        self.enterInputFilePushButton_2.setGeometry(QtCore.QRect(490, 70, 71, 31))
        self.enterInputFilePushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: 0;\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(239, 239, 239);\n"
"color: rgb(255, 255, 255);")
        self.enterInputFilePushButton_2.setObjectName("enterInputFilePushButton_2")
        self.fileName_2 = QtWidgets.QLabel(Dialog)
        self.fileName_2.setGeometry(QtCore.QRect(10, 70, 471, 31))
        self.fileName_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: 2px solid;\n"
"color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(253, 5, 158, 255), stop:1 rgba(255, 230, 37, 255));\n"
"background-color: 0;\n"
"border-radius: 0px;")
        self.fileName_2.setObjectName("fileName_2")
        self.prognosButton = QtWidgets.QPushButton(Dialog)
        self.prognosButton.setGeometry(QtCore.QRect(170, 230, 141, 31))
        self.prognosButton.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"background-color: 0;\n"
"border: 2px solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(253, 5, 158, 255), stop:1 rgba(255, 230, 37, 255));\n"
"background-color: 0;\n"
"color: rgb(255, 255, 255);")
        self.prognosButton.setObjectName("prognosButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 391, 21))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: 0;")
        self.label.setObjectName("label")
        self.fileName = QtWidgets.QLabel(Dialog)
        self.fileName.setGeometry(QtCore.QRect(10, 30, 471, 31))
        self.fileName.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border: 2px solid;\n"
"color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(253, 5, 158, 255), stop:1 rgba(255, 230, 37, 255));\n"
"background-color: 0;\n"
"border-radius: 0px;")
        self.fileName.setObjectName("fileName")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 411, 21))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: 0;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 381, 31))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: 0;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 200, 191, 21))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: 0;")
        self.label_4.setObjectName("label_4")
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(480, 230, 81, 31))
        self.closeButton.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"background-color: 0;\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(239, 239, 239);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.enterInputFilePushButton.raise_()
        self.enterInputFilePushButton_2.raise_()
        self.prognosButton.raise_()
        self.label.raise_()
        self.fileName_2.raise_()
        self.fileName.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.closeButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prognosing Model"))
        self.enterInputFilePushButton.setText(_translate("Dialog", "Открыть"))
        self.enterInputFilePushButton_2.setText(_translate("Dialog", "Открыть"))
        self.fileName_2.setText(_translate("Dialog", " Выберите файл с информацией об ожидаемых поставках"))
        self.prognosButton.setText(_translate("Dialog", "ОК"))
        self.label.setText(_translate("Dialog", "После ввода данных нажмите на кнопку ОК"))
        self.fileName.setText(_translate("Dialog", " Выберите файл с информацией о плане"))
        self.label_2.setText(_translate("Dialog", "Если данные отсутствуют, то расчет графиков"))
        self.label_3.setText(_translate("Dialog", "будет производиться по общим данным со "))
        self.label_4.setText(_translate("Dialog", "скадов прошлых лет"))
        self.closeButton.setText(_translate("Dialog", "Выйти"))
